language: cpp

addons:
  apt:
    packages:
      - cxxtest

script:
  - cmake .
  - make
  - cd tests/
  - cxxtestgen --xunit-printer -o runner.cpp tests.cpp
  - g++ -std==c++11 -L. -lopenssl-gcb -lcrypto ./runner.cpp -o runner
  - ./runner
